## Creating NumPy Arrays

### Why NumPy Arrays?

NumPy arrays are the core of numerical computing in Python. They are:

- Faster than Python lists (C-optimized)
- Memory-efficient (store data in a contiguous block)
- Support vectorized operations that support SIMD (no slow Python loops)
- Used in ML, Data Science, and AI

### 1. Creating NumPy Arrays

**From Python Lists:**

```python
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])           # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])    # 2D array

print(arr1)  # [1 2 3 4 5]
print(arr2)  # [[1 2 3]
             #  [4 5 6]]
```

🔹 Unlike lists, all elements must have the same data type.

**Creating Arrays from Scratch:**

```python
np.zeros((3, 3))      # 3x3 array of zeros
np.ones((2, 4))       # 2x4 array of ones
np.full((2, 2), 7)    # 2x2 array filled with 7
np.eye(4)             # 4x4 identity matrix
np.arange(1, 10, 2)   # [1, 3, 5, 7, 9] (like range)
np.linspace(0, 1, 5)  # [0. 0.25 0.5 0.75 1.] (evenly spaced)
```

**Key Takeaway:** NumPy offers powerful shortcuts to create arrays without loops!

### 2. Checking Array Properties

```python
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape)      # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)        # 6 → total elements
print("Dimensions:", arr.ndim)  # 2 → 2D array
print("Data type:", arr.dtype)  # int64 (or int32 on Windows)
```

🔹 NumPy arrays are strongly typed, meaning all elements share the same data type.

### 3. Changing Data Types

```python
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]
```

- Efficient memory usage by choosing the right data type.

### 4. Reshaping and Flattening Arrays

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]

flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)  # [1 2 3 4 5 6]
```

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])

In [3]:
arr

array([1, 2, 3])

In [4]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((4, 6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [10]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [11]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [12]:
myarr.shape

(4, 3)

In [13]:
myarr.size

12

In [15]:
myarr.ndim

2

In [16]:
myarr.dtype

dtype('int64')

In [17]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype='float32')

In [18]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [20]:
n = myarr.astype('float64')

In [21]:
n.dtype

dtype('float64')

In [22]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [23]:
myarr.shape

(4, 3)

In [24]:
reshaped = myarr.reshape((3, 4))

In [25]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])