## Indexing and Slicing

Let's now learn about indexing and slicing in NumPy.

### Indexing (Same as Python Lists)

```python
arr = np.array([10, 20, 30, 40])
print(arr[0])   # 10
print(arr[-1])  # 40
```

### Slicing (Extracting Parts of an Array)

```python
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)
```

> **Slicing returns a view, not a copy!** Changes affect the original array.

This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a **view** of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

**Why does this happen?**

- **Memory Efficiency** — Avoids unnecessary copies, making operations faster and saving memory.
- **Performance** — Enables faster access and manipulation of large datasets without duplicating data.

```python
sliced = arr[1:4]
sliced[0] = 999
print(arr)  # [10 999 30 40 50]
```

- Use `.copy()` if you need an independent copy.

---

## 6. Fancy Indexing & Boolean Masking

### Fancy Indexing (Select Multiple Elements)

```python
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]
```

### Boolean Masking (Filter Data)

```python
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]
```

This is a powerful way to filter large datasets efficiently!

---

## Summary

- NumPy arrays are faster, memory-efficient alternatives to lists.
- You can create arrays using `np.array()`, `np.zeros()`, `np.ones()`, etc.
- Indexing & slicing allow efficient data manipulation.
- Reshaping & flattening change array structures without copying data.
- Fancy indexing & boolean masking help filter and access specific data.

In [20]:
import numpy as np
np.set_printoptions(legacy="1.25")

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
flat = arr.flatten()

In [10]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
flat[4]

5

In [22]:
flat[3: 6]

array([4, 5, 6])

In [23]:
flat[ :5]

array([1, 2, 3, 4, 5])

In [24]:
flat[4: ]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
b = flat[4: 11].copy()

In [26]:
b

array([ 5,  6,  7,  8,  9, 10, 11])

In [29]:
b[0] = 22270

In [30]:
flat

array([    1,     2,     3,     4, 22270,     6,     7,     8,     9,
          10,    11,    12])

In [31]:
arr = np.array([1, 42, 56, 87, 98, 25])

In [35]:
arr[[2, 4, 5]]

array([56, 98, 25])

In [37]:
arr[arr > 50]

array([56, 87, 98])

# Exercises for Practice

- Create a 3×3 array filled with random numbers and print its shape.
- Convert an array of floats [1.1, 2.2, 3.3] into integers.
- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
- Reshape a 1D array of size 9 into a 3×3 matrix.
- Use boolean masking to filter numbers greater than 50 in an array.

In [76]:
#1
a = np.random.randint(1, 100, size = (3, 3))

print(a)

[[62 94 96]
 [68 90 92]
 [59 52 95]]


In [77]:
a.shape

(3, 3)

In [78]:
#2
f = np.array([1.1, 2.2, 3.3])


In [79]:
f

array([1.1, 2.2, 3.3])

In [80]:
f.astype('int32')

array([1, 2, 3], dtype=int32)

In [87]:
i = np.array([1, 2, 3, 4, 5, 6])
mask = i % 2 == 0
even = i[mask]

In [88]:
even

array([2, 4, 6])

In [94]:
#4

myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [95]:
arr = myarr.reshape((3, 3))

In [96]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
myarr = np.array([[1, 230, 3], [4, 56, 60], [7, 89, 9]])

In [99]:
myarr[myarr > 50]

array([230,  56,  60,  89])