# Broadcasting in NumPy

Now, we'll explore how to make your code faster with **vectorization** and **broadcasting** in NumPy. These techniques are key to boosting performance in numerical operations by avoiding slow loops and memory inefficiency.

---

## 1. Why Loops Are Slow

In Python, loops are typically slow because:

- **Python's interpreter** — Every iteration requires Python to interpret the loop logic, which is inherently slower than lower-level, compiled code.
- **High overhead** — Each loop iteration involves additional overhead for function calls, memory access, and index management.

While Python loops are convenient, they don't take advantage of the optimized memory and computation that libraries like NumPy provide.

### Example: Looping Over Arrays in Python

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = []

# Using a loop to square each element (slow)
for num in arr:
    result.append(num ** 2)

print(result)  # Output: [1, 4, 9, 16, 25]
```

> ⚠️ This works, but it's not efficient. Each loop iteration is slow, especially with large datasets.

---

## 2. Vectorization: Fixing the Loop Problem

**Vectorization** allows you to perform operations on entire arrays at once, instead of iterating over elements one by one. This is made possible by NumPy's optimized C-based backend that executes operations in compiled code — much faster than Python loops.

Vectorized operations are also more **readable** and **compact**, making your code easier to maintain.

### Example: Vectorized Operation

```python
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2  # Vectorized operation
print(result)  # Output: [ 1  4  9 16 25]
```

Here, the operation is applied to **all elements simultaneously** — much faster than looping.

### Why is it Faster?

| Reason | Explanation |
|--------|-------------|
| Low-level implementation | NumPy's operations are written in C (compiled), far faster than Python |
| Batch processing | Uses **SIMD** (Single Instruction, Multiple Data) to process multiple elements in parallel |

---

## 3. Broadcasting: Scaling Arrays Without Extra Memory

**Broadcasting** is a powerful NumPy feature that allows you to perform operations on arrays of different shapes without creating copies. It "stretches" smaller arrays across larger arrays in a memory-efficient way.

### Example: Broadcasting with a Scalar

```python
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10  # 10 is broadcast across all elements
print(result)  # Output: [11 12 13 14 15]
```

> The scalar `10` is "broadcast" across the entire array — no extra memory used. ✅

---

## 4. Broadcasting with Arrays of Different Shapes

Broadcasting becomes more powerful when applied to arrays of different shapes. NumPy automatically adjusts shapes to make them compatible for element-wise operations — without copying data.

### Example: Broadcasting Two 1D Arrays

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2  # Element-wise addition
print(result)  # Output: [11 22 33]
```

### Example: Broadcasting a 2D Array and a 1D Array

```python
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # arr2 is broadcast across rows of arr1
print(result)
# Output:
# [[2 4 6]
#  [5 7 9]]
```

Here, `arr2` is broadcast across **each row** of `arr1`, adding `[1, 2, 3]` to every row.

### How Broadcasting Works

- **Dimensions must be compatible** — The size of trailing dimensions must either match or one of them must be `1`.
- **Stretching arrays** — NumPy stretches the smaller array to match the larger one, element-wise, without copying data.

---

## 5. Real-World Example: Normalizing Data

Let's apply broadcasting to a real-world scenario: **scaling data in machine learning**.

### Example: Normalizing a Dataset

Imagine a dataset where each row is a sample and each column is a feature. You can normalize by subtracting the column mean and dividing by the standard deviation.

```python
import numpy as np

# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std  = data.std(axis=0)

# Normalizing using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)
```

> Broadcasting lets you subtract the mean and divide by std **for each feature simultaneously** — no loops, no extra memory copies. 🚀

---

## 6. Summary

| Concept | Key Point |
|---------|-----------|
| **Loops** | Slow due to Python interpreter overhead |
| **Vectorization** | Applies operations to entire arrays at once using NumPy's C backend |
| **Broadcasting** | Performs operations on different-shaped arrays without copying data |
| **Real-world use** | Data normalization, scaling, and feature engineering in data science |

- Use **vectorization** to replace loops and speed up numerical operations.
- Use **broadcasting** to work with arrays of different shapes efficiently.
- Together, they make NumPy the go-to tool for high-performance data science. 🎯

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2  # Vectorized operation
print(result)  # Output: [ 1  4  9 16 25]

[ 1  4  9 16 25]


In [3]:
result + 10

array([11, 14, 19, 26, 35])

In [4]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # arr2 is broadcast across rows of arr1
print(result)

[[2 4 6]
 [5 7 9]]


In [5]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std  = data.std(axis=0)

# Normalizing using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
